### ISSUE TITLE
customizer.sh not working on Ubuntu

### ISSUE THREAD

**Issue by Arthur-Melnik** [android/architecture-templates#110]
Unfortunately, I was not able to run customizer script on Ubuntu 22.04 (Installed under Windows 11), with GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu), getting the following errors, does bash should be exactly version 4? Or does it works only on macos? If so would be nice to have linux/windows versions of the script

```
bash customizer.sh com.sample.app SampleDataItem [Sample App]
customizer.sh: line 17: $'\r': command not found
customizer.sh: line 19: syntax error in conditional expression
'ustomizer.sh: line 19: syntax error near `]]
'ustomizer.sh: line 19: `if [[ ${BASH_VERSINFO[0]} -lt 4 ]]
```

**Comment by Arthur-Melnik** [comment]
Upd. I was able to run script after changing line ending of script from CRLF to LF

**Comment by JoseAlcerreca** [comment]
Is that all that's needed to make it compatible?
