### ISSUE TITLE
Change structure package to using subfolder in multimodule template

### ISSUE THREAD

**Issue by wiryadev** [android/architecture-templates#19]
I think it would be better to change the `core-foo` to `core/foo` like in the NowInAndroid latest update. My reason is so that the root project doesnt get bloated with all of `core-foo` and `feature-bar`. So it would look like this:
![image](https://user-images.githubusercontent.com/26060382/189519279-48cc5f4e-98c8-4161-a686-e125254cf295.png)

**Comment by JoseAlcerreca** [comment]
We decided against it because it reduces discoverability. Thanks for the feedback though, we'll keep it in mind and track the dups and +1s.
