### ISSUE TITLE
Android Studio Create New Module does not work

### ISSUE THREAD

**Issue by ashrafi** [android/architecture-templates#48]
Try to create a new feature module from Android Studio using the menu does not work.

Get error:

A problem occurred configuring root project 'Multimodule template'.
> Could not resolve all files for configuration ':classpath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20 because no repositories are defined.
     Required by:
         project :

**Comment by ashrafi** [comment]
But it is normal part of just using Android Studio ... 
The project should work like any other normal project, right?
Creating a new module should not cause an error ... right? Or am I missing something
All we do is just use the pull down menu in Android Studio to create a new model and it generated the error ...

**Comment by pablichjenkov** [comment]
That is an Intellij/Android issue, when adding a module using the IDE file/new module some files are wrongly generated by the IDE. The solution, add the module manually, copy and paste one of the module and change names and add it in the settings.gradle.kts file.

**Comment by ashrafi** [comment]
Yes ... that is what we do now ... just hoping it would be fix so we can use the pull-down menu item.
Thanks :-)
