### ISSUE TITLE
Reconsider usage of Renovate, given it is under AGPL license.

### ISSUE THREAD

**Issue by yogurtearl** [android/architecture-templates#62]
Might want to reconsider the usage of [Renovate](https://github.com/android/architecture-templates/pulls?q=is%3Apr+author%3Aapp%2Frenovate)

Related to this policy: https://opensource.google/documentation/reference/using/agpl-policy

Given this license: https://github.com/renovatebot/renovate/blob/main/license

(feel free to close this issue out as appropriate)

**Comment by JoseAlcerreca** [comment]
Thanks for the flag Michael! I checked and it's all good.
