### ISSUE TITLE
Support in Android Studio templates

### ISSUE THREAD

**Issue by madroidmaq** [android/architecture-templates#65]
It is expected to support new projects in Android Studio, as shown in the figure below

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/6247142/215385846-ab6550ab-e622-42d1-b34b-1dddb6b7327f.png">

**Comment by JoseAlcerreca** [comment]
At some point, yes. See blog post for more info https://medium.com/androiddevelopers/introducing-the-architecture-templates-3151323e4e34
